### ISSUE TITLE
Upgrade to JDK 8

### ISSUE THREAD

**Issue by cbeams** [spring-io/sagan#181]
Tracking issue. Individual tasks will be created for the application of each new aspect of upgrading Sagan to JDK 8, and linked to from here.
- [x] JDK 8 Cloud Foundry buildpack (#148)
- [x] Update travis config to build with openjdk8 (#348)
- [x] Update build.gradle to build at 1.8 language level  (#348)
- [x] Refactor to take advantage of new language features  (#348)
- [x] Ensure Eclipse and IDEA metadata is generated to expect 1.8
- [x] Update Java requirements in the wiki
